# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b597bd405031e73bf8da61c3dca5d1af7e53bda5622dd38fdf5295cbc58720fa90e5a2829c5a801f65d36af5c91d8d5fab724553bd4e3bba21f1ef0ea791af4

test:
  secret_key_base: 846da65af0c91bfc116f98ca4ec86682f743f5c6bbb26983ec1e429ceb45fd3112d7a5c00f1aace772145337ad475b4fb1dc740dce294d01f15f8d03626ce70b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
